apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: mongo-config
              mountPath: /config
            - name: mongo-credentials
              mountPath: /etc/mongo-credentials
      volumes:
        - name: mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongodb-secret-mount
          secret:
            secretName: mongo-secret
        - name: mongodb-config-mount
          configMap:
            name: mongo-configmap
            items:
              - key: mongo.conf
                path: mongo.conf
