apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
    spec:
      containers:
        - name: karsajobs
          image: karsajobs-backend:karsajobs-backend
          ports:
            - containerPort: 5000
          env:
            - name: APP_PORT
              value: "8080"
